stable/coredns/Chart.yaml, stable/coredns/templates/deployment.yaml, stable/coredns/templates/serviceaccount.yaml, stable/coredns/values.yaml
This PR adds support for passing ServiceAccount annotations, which is required for example to deploy CoreDNS on AWS EKS with IAM Role ARN in annotations.
Furthermore, this PR also fixes #3.
=> Add support for ServiceAccount annotations

stable/coredns/Chart.yaml, stable/coredns/templates/deployment.yaml, stable/coredns/values.yaml
This allows to set different values outside for the deployment through helm.
=> Extract ready/livenessProbe settings to values

.github/workflows/release.yaml
The path to charts is wrong, so the chart-releaser looks to wrong folder.
I've stripped the last slash, so chart releaser is now checking the right folder.
fixes #16
https://github.com/helm/chart-releaser-action/blob/120944e66390c2534cc1b3c62d7285ba7ff02594/cr.sh#L228
=> chore: fix release path

charts/coredns/Chart.yaml, charts/coredns/templates/configmap.yaml, charts/coredns/values.yaml
With this change it is possible to extra/custom config options
outside of the zones block which enables some further/advanced
customization.
=> Allow to add extra config to the default Corefile

charts/coredns/Chart.yaml, charts/coredns/templates/_helpers.tpl, charts/coredns/values.yaml
This will add support to specify nodePort when serviceType is nodePort
Signed-off-by: Seena Fallah <seenafallah@gmail.com>
Signed-off-by: Yasin Lachini <yasin.lachiny@gmail.com>
=> service: add support nodePort for service ports

charts/coredns/Chart.yaml, charts/coredns/templates/configmap-autoscaler.yaml, charts/coredns/templates/deployment.yaml, charts/coredns/templates/service-metrics.yaml, charts/coredns/templates/service.yaml, charts/coredns/templates/serviceaccount.yaml
It was easy to result in an invalid yaml error if you set some values. For example:  if you only set `prometheus.service.enabled` to `true` the yaml in service-metrics.yaml is invalid, or if you set something in `customAnnotations` many files could result in invalid yaml.
fix #60
=> Fix annotations generating invalid yaml

charts/coredns/Chart.yaml, charts/coredns/values.yaml
This sets the hpa.metrics key to its correct default value. Which is an array and not a dict. Having it as a dict. gives issues as seen in #79. Which I hope to solve with this PR.
See: https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/horizontal-pod-autoscaler-v2/#HorizontalPodAutoscalerSpec for the official ref. docs on HPA and the `metrics` key type specifically.
Thank you.
=> Defalt val. of hpa.metrics to the correct type

charts/coredns/templates/_helpers.tpl
This automatically creates an additional container port if prometheus has been defined inside the plugins section.
Containers should export all ports if they are used. We found this issue with https://github.com/derailed/popeye
=> Add prometheus port to the container, Fixes #46

charts/coredns/templates/service.yaml
When using `services.externalIPs`, the service template isn't rendered correctly.
```yaml
spec:
{{- if .Values.service.externalIPs }}
externalIPs:
{{ toYaml .Values.service.externalIPs | indent 4 }}
{{- end }}
```
Given the following `values.yaml` :
```yaml
services:
externalIPs:
- 1.2.3.4
- 2.3.4.5
```
The template will render as such :
```yaml
spec:
externalIPs:
- 1.2.3.4
- 2.3.4.5
```
This comes from the fact that `indent` doesn't remove leading spaces for the first rendered line.
Proposed solution removes leading whitespace (including newlines) by using the left chomping modifier, and uses `nindent` to render a 4-space indented list prepended by a newline.
=> fix: externalIPs indentation

charts/coredns/Chart.yaml, charts/coredns/templates/deployment.yaml, charts/coredns/values.yaml
This is needed to allow configuration of the pod level securityContext. The pod level security context can be useful for setting things like seccompProfile at the pod level.
N/A
Checklist:
<details>
=> Add ability to configure pod level securityContext

charts/coredns/Chart.yaml, charts/coredns/templates/deployment-autoscaler.yaml, charts/coredns/templates/deployment.yaml
spec.template.metadata.annotations[scheduler.alpha.kubernetes.io/critical-pod]: non-functional in v1.16+; use the "priorityClassName" field instead
Checklist:
<details>
=> Remove deprecated critical-pod annotation

charts/coredns/Chart.yaml, charts/coredns/templates/deployment-autoscaler.yaml, charts/coredns/values.yaml
Allows for specifying annotations on coredns autoscaler pods
Fixes #123 
Checklist:
<details>
=> Add podAnnotations for autoscaler

charts/coredns/Chart.yaml, charts/coredns/templates/_helpers.tpl, charts/coredns/templates/clusterrole-autoscaler.yaml, charts/coredns/templates/clusterrole.yaml, charts/coredns/templates/clusterrolebinding-autoscaler.yaml, charts/coredns/templates/clusterrolebinding.yaml, charts/coredns/templates/configmap-autoscaler.yaml, charts/coredns/templates/configmap.yaml, charts/coredns/templates/deployment-autoscaler.yaml, charts/coredns/templates/deployment.yaml, charts/coredns/templates/hpa.yaml, charts/coredns/templates/poddisruptionbudget.yaml, charts/coredns/templates/podsecuritypolicy.yaml, charts/coredns/templates/service-metrics.yaml, charts/coredns/templates/service.yaml, charts/coredns/templates/serviceaccount-autoscaler.yaml, charts/coredns/templates/serviceaccount.yaml, charts/coredns/templates/servicemonitor.yaml
It would move the labels from the resource manifest to a single helpers.tlp which would make that handling of these labels much more simplified 
https://github.com/coredns/helm/issues/104
Checklist:
<details>
=> [Refactor] - Move labels to helpers.tpl

.github/workflows/lint-test.yaml, charts/coredns/Chart.yaml
This PR would be essential to check pass the failing lint test that is occurring while fixing https://github.com/coredns/helm/issues/103
https://github.com/coredns/helm/actions/runs/5716180247/job/15487114422
Checklist:
<details>
=> [Update] - Github Actions

charts/coredns/Chart.yaml, charts/coredns/templates/servicemonitor.yaml
when set prometheus.monitor.namespace to differ namespace, we should use namespaceSelector to specify service namespace
Checklist:
<details>
=> fix wrong namespaceSelector in servicemonitor

charts/coredns/Chart.yaml
Upgrade CoreDNS to version 1.11.1 to address a recently found regression, see the [coredns release notes](https://github.com/coredns/coredns/releases/tag/v1.11.1)
Checklist:
<details>
=> Upgrade coredns app version to 1.11.1

.github/workflows/lint-test.yaml, .github/workflows/release.yaml
Update workflows to use environment file instead of deprecated set-output command.
For more information, see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Also bump the `helm` version used in the workflows
Fix #138 
Checklist:
<details>
=> Replace set-output with environment file for workflows

charts/coredns/Chart.yaml, charts/coredns/templates/deployment-autoscaler.yaml, charts/coredns/templates/deployment.yaml
#141 added support for sidecar containers, but the indentation is wrong. This fixes it so the template can render correctly.
Issue caused from #141 if using the `extraContainers` field.
Checklist:
<details>
=> fix indentation for extraContainers

charts/coredns/Chart.yaml, charts/coredns/templates/deployment.yaml, charts/coredns/values.yaml
This request is needed because the `defaultMode` value of `400` is hardcoded into the [deployment.yaml file](https://github.com/coredns/helm/blob/master/charts/coredns/templates/deployment.yaml#L156) for any secrets defined in  `.Values.extraSecrets` which causes the CoreDNS pod to crash loop when using etcd as a back end with a "permission denied" error for the file mounted.  Changing this to `420` resolves the issue, but the user should be able to set the `defaultMode` using the values file.  This exposes the setting but uses a default of `400`.
https://github.com/coredns/helm/issues/144
Checklist:
<details>
If the DCO action in the integration test fails, one or …
=> Ability to override defaultMode for extraSecrets

charts/coredns/Chart.yaml, charts/coredns/templates/configmap.yaml, charts/coredns/templates/deployment.yaml, charts/coredns/templates/hpa.yaml, charts/coredns/templates/poddisruptionbudget.yaml, charts/coredns/templates/service-metrics.yaml, charts/coredns/templates/service.yaml, charts/coredns/templates/serviceaccount.yaml
Adding .Release.Namespace in metadata fixes issues when rendering template with 'helm template --namespace'. Without it, the rendered templates do not have the namespace defined which is problematic when using a gitops approach.
Checklist:
=> fix: add .Release.Namespace in metadata

charts/coredns/Chart.yaml, charts/coredns/templates/_helpers.tpl
Current chart was setting not smart names for all object it was creating.
Specifically if release name equals chart name - in this case `coredns` - release name should be ignored, to avoid duplicates in the name.
- Before the fix: names with `coredns-coredns` string in them.
```txt
kubectl -n kube-system get all,sa,clusterrole,clusterrolebinding,smon -l app.kubernetes.io/instance=coredns
NAME                                   READY   STATUS    RESTARTS      AGE
pod/coredns-coredns-6db9976d78-drpdc   1/1     Running   1 (11h ago)   15h
NAME                              TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)         AGE
service/coredns-coredns-metrics   ClusterIP   10.30.232.118   <none>        9153/TCP        15h
service/kube-dns                  ClusterIP   10.30.0.10 …
```
=> Ignore duplicate strings in the fullname helper template

charts/coredns/Chart.yaml, charts/coredns/templates/configmap.yaml, charts/coredns/values.yaml
A requested rebase and merge from PR #41
Checklist:
<details>
=> Allow to skip ConfigMap creation

charts/coredns/Chart.yaml, charts/coredns/templates/service.yaml, charts/coredns/values.yaml
This pull request adds a value for configuring the service's `loadBalancerClass` field. This allows the chart to easily be deployed in environments that have multiple load balancers that could potentially satisfy Kubernetes LoadBalancer services. 
Checklist:
<details>
=> added: support service loadBalancerClass

charts/coredns/Chart.yaml, charts/coredns/templates/_helpers.tpl, charts/coredns/values.yaml
This PR allows exposing coreDNS on a service port different from the ports exposed by the container.
We want to expose coreDNS publicly. To increase security we would like to open a container port above 1024 to not add the `NET_BIND_SERVICE` capability, while still exposing the service on port 53.
The change adds an optional `servers.servicePort` key that can be used to set a service port. If this value is not set, the value of the `servers.port` is used both as service and container port (old behavior). Thus, the change is fully backwards compatible.
```
helm package . && helm template coredns coredns-1.33.0.tgz -f values.yaml > manifests2.yaml
...
diff manifests.yaml manifests2.yaml                                                        
111,112c111,112
<   - …
```
=> Support different service and container ports

charts/coredns/Chart.yaml, charts/coredns/values.yaml
Fix a minor documentation oops on my last PR #176, in `values.yaml` the new `trafficDistribution` key was at `prometheus.service` instead of `service`, apologies for the noise.
None
Checklist:
<details>
=> Fix `trafficDistribution` documentation issue

charts/coredns/Chart.yaml, charts/coredns/values.yaml
This addresses a templating error by adding a default value to the chart.
A thing the maintainers of this repo likely already know but that I felt the need to check while making this PR: setting a Helm value to an empty string results in it being treated as false in if/else statements (https://helm.sh/docs/chart_template_guide/control_structures/#ifelse). So this should be a safe default.
https://github.com/coredns/helm/issues/180
Checklist:
=> fix: add default value for clusterRole name override

charts/coredns/Chart.yaml, charts/coredns/README.md
"labels" is [plural](https://kubernetes.io/docs/reference/kubernetes-api/common-definitions/object-meta/).
Checklist:
<details>
=> Fix typo for labels in README.md

charts/coredns/Chart.yaml, charts/coredns/templates/deployment.yaml
The `Deployment` object has a label named `app.kubernetes.io/version` which value is `Chart.AppVersion`. But this is not always true because the chart allows to specify the image tag with the `image.tag`.
I think it makes more sense to use the same mechanism as with the image tag. Use `Chart.AppVersion` by default but use `image.tag` if present.
n/a
Checklist:
<details>
=> Use image.tag for app.kubernetes.io/version label if defined

charts/coredns/Chart.yaml, charts/coredns/templates/deployment.yaml
A bug was introduced in release `v1.37.2` that made helm fail when using a docker inmutable tag as `v1.12.0@sha256:40384aa1f5ea6bfdc77997d243aec73da05f27aed0c5e9d65bfa98933c519d97`. This happened because there are some restrictions documented in kubernetes labels ([documentation](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set)), e.g. a length of 63 characters, only alphanumeric and `_`, `-` and `.` characters.
This PR attempts to fix the problem described above. Some filters were added to filter out the invalid characters present in a docker inmutable label (`@` and `:`), and the length truncated to 63 characters.
- https://github.com/coredns/helm/issues/191
Checklist:
Changes are automatically published when merged to `main`. They are …
=> Fix helm install when using docker inmutable tags

.github/workflows/release.yaml, charts/coredns/Chart.yaml, charts/coredns/README.md
- Adds publishing of coredns chart to ghcr.io registry
- Adds cosign keyless signing to actions
- fixes #182
Checklist:
<details>
=> feat(oci): add publishing of helm chart to oci repo

.github/workflows/release.yaml, charts/coredns/Chart.yaml
Fix missing permissions from pr #189
- Recent build failure
Checklist:
<details>
=> hotfix(actions): add missing permissions for publishing to ghcr.io

charts/coredns/Chart.yaml
Bumps CoreDNS to v1.12.0
-
Checklist:
<details>
=> Bump to v1.12.0

charts/coredns/Chart.yaml, charts/coredns/templates/deployment-autoscaler.yaml, charts/coredns/templates/deployment.yaml, charts/coredns/templates/serviceaccount-autoscaler.yaml, charts/coredns/templates/serviceaccount.yaml
Fixes the misalignment between the structure expected for `image.pullSecrets` in `deployment.yaml`/`deployment-autoscaler.yaml` and `serviceaccount.yaml`/`serviceaccount-autoscaler.yaml` which made it impossible to use  imagePullSecrets because they produced invalid manifests.
I also took the opportunity to align the `if` statements in the `Deployment` templates to what is used in the `ServiceAccount` templates for consistency.
Fixes https://github.com/coredns/helm/issues/154
Checklist:
<details>
If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions …
=> fix: align imagePullSecrets in Deployment and ServiceAccount

charts/coredns/Chart.yaml, charts/coredns/templates/_helpers.tpl
Creating DoH listener via chart tries to use both TCP and UDP for the service, while only TCP is appropriate. Trying to expose such service via load balancer in some cloud providers leads to issues with no ability to create TCP and UDP listeners on the same port.
This PR adds `https://` to TCP-only scheme list.
Checklist:
<details>
=> fix supported schemes: add https:// to tcp-only scheme list

charts/coredns/Chart.yaml, charts/coredns/values.yaml
Update cpa/cluster-proportional-autoscaler to v1.9.0
Changelogs:
- https://github.com/kubernetes-sigs/cluster-proportional-autoscaler/releases/tag/1.8.6
- https://github.com/kubernetes-sigs/cluster-proportional-autoscaler/releases/tag/v1.8.8
- https://github.com/kubernetes-sigs/cluster-proportional-autoscaler/releases/tag/v1.8.9
- https://github.com/kubernetes-sigs/cluster-proportional-autoscaler/releases/tag/v1.9.0
Diff:
- https://github.com/kubernetes-sigs/cluster-proportional-autoscaler/compare/1.8.5...v1.9.0
N/A
Checklist:
=> fix(deps): update cpa/cluster-proportional-autoscaler to v1.9.0

.github/workflows/lint-test.yaml, charts/coredns/.helmignore, charts/coredns/Chart.yaml, charts/coredns/README.md, charts/coredns/tests/clusterrole-autoscaler_test.yaml, charts/coredns/tests/clusterrole_test.yaml, charts/coredns/tests/clusterrolebinding_autoscaler_test.yaml, charts/coredns/tests/clusterrolebinding_test.yaml, charts/coredns/tests/configmap_autoscaler_test.yaml, charts/coredns/tests/configmap_test.yaml, charts/coredns/tests/deployment-autoscaler_test.yaml, charts/coredns/tests/deployment_test.yaml, charts/coredns/tests/hpa_test.yaml, charts/coredns/tests/poddisruptionbudget_test.yaml, charts/coredns/tests/service-metrics_test.yaml, charts/coredns/tests/service_test.yaml, charts/coredns/tests/serviceaccount_autoscaler_test.yaml, charts/coredns/tests/serviceaccount_test.yaml, charts/coredns/tests/servicemonitor_test.yaml
- Added unit tests for ClusterRole, ClusterRoleBinding, ConfigMap, Deployment, HPA, PDB, Service, ServiceMonitor, and ServiceAccount
- Included autoscaler-specific test files
- Updated GitHub Actions workflow to run chart testing
fix #208 
Checklist:
<details>
=> Added Helm unit tests for CoreDNS chart components

charts/coredns/Chart.yaml, charts/coredns/templates/_helpers.tpl
This pull request is duplicate of [PR 23](https://github.com/coredns/helm/pull/23). Since original PR 23 contributor @k0da does not respond on request to rebase and bump chart version, I decided to create additional PR.
> According to [values.yaml](https://github.com/coredns/helm/blob/master/charts/coredns/values.yaml#L148)
> dns:// is supposed to be udp only with optional tcp enablement through
> use_tcp flag.
Related to [PR 23](https://github.com/coredns/helm/pull/23)
Checklist:
<details>
If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on …
=> Fix default ports for dns:// scheme [rebased]

charts/coredns/Chart.yaml, charts/coredns/templates/_helpers.tpl
It's completes changes of previous [PR 211](https://github.com/coredns/helm/pull/211)
Fix default ports for dns:// scheme of "coredns.containerPorts" definition in (`_helper.tpl`)
Thanks to @IdlePhysicist https://github.com/coredns/helm/pull/211#issuecomment-2864547502
>According to [values.yaml](https://github.com/coredns/helm/blob/master/charts/coredns/values.yaml#L148)
>dns:// is supposed to be udp only with optional tcp enablement through
>use_tcp flag.
Related to [PR 211](https://github.com/coredns/helm/pull/211), namely to https://github.com/coredns/helm/pull/211#issuecomment-2864547502
Checklist:
<details>
If the DCO action in the integration test fails, one …
=> Fix default ports for dns:// scheme of coredns.containerPorts definition

charts/coredns/Chart.yaml, charts/coredns/templates/_helpers.tpl, charts/coredns/values.yaml
Undefined `scheme` defaults to `scheme: dns://`, and tcp port enabled by default with `use_tcp: true` in [values.yaml](https://github.com/coredns/helm/blob/master/charts/coredns/values.yaml)
Related to [212](https://github.com/coredns/helm/issues/212)
Checklist:
<details>
=> Default udp fix

charts/coredns/Chart.yaml, charts/coredns/templates/serviceaccount.yaml
This adds support for the `customLabels` field in the `ServiceAccount` object
Fixes #222
Checklist:
<details>
=> fix: Add support for customLabels to ServiceAccount

charts/coredns/Chart.yaml
Bumps coredns to 1.12.3
Checklist:
<details>
=> chore: Bump coredns to 1.12.3

charts/coredns/Chart.yaml, charts/coredns/templates/deployment.yaml
The chart does not support the following values 
```yaml
affinity:
podAntiAffinity:
requiredDuringSchedulingIgnoredDuringExecution:
- labelSelector:
matchLabels:
app.kubernetes.io/instance: "{{ .Release.Name }}"
app.kubernetes.io/name: '{{ template "coredns.name" . }}'
```
This change is necessary to avoid hardcoding those labels.
None
Checklist:
<details>
=> fix: use tpl function for affinity values
